# Generated by Django 4.2.4 on 2023-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo_api', '0004_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('timestamp_creation', models.DateField(auto_now_add=True)),
                ('timestamp_updated', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('F', 'Not completed'), ('T', 'Completed')], default='F', max_length=1)),
            ],
        ),
    ]
